apiVersion: rhpam.kiegroup.org/v1
kind: KogitoBuild
metadata:
  name: dmn-springboot-example
spec:
  type: RemoteSource
  runtime: springboot
  #env:
  # env can be used to set variables during build
  #- name: MY_CUSTOM_ENV
  #  value: "my value"
  gitSource:
    contextDir: kogito-springboot-examples/dmn-springboot-example
    uri: 'https://github.com/alpha-wolf-jin/kogito-examples-01'
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL: 
---
apiVersion: rhpam.kiegroup.org/v1
kind: KogitoRuntime
metadata:
  name: dmn-springboot-example
spec:
  runtime: springboot

